version: '3.0'

services:
  backend:
    container_name: backend
    restart: always
    build: .
    ports:
      - "4000:4100"
    links:
      - rabbitmq
    networks:
      hosts:
  rabbitmq:
    image: rabbitmq:3.10-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      hosts:

networks:
  hosts: