# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  testes:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B test --file ./mscompras/pom.xml
  
  build:
    needs: testes
    name: Build Maven package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/
          key: ${{ runner.os }}-maven-${{ hashFiles('./mscompras/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: build with maven jar
        run: mvn -B package -DskipTests --file ./mscompras/pom.xml
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          # Artifact name
          name: artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: ./mscompras/target/app.jar
  # deploy:
  #   needs: build
  #   name: Deploy on aws 
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: download jar
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: artifact
  #     - name: Deploy to EB
  #       uses: einaregilsson/beanstalk-deploy@v20
  #       with:
  #         aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         wait_for_environment_recovery: 120
  #         use_existing_version_if_available: true
  #         application_name: MyApplicationName
  #         environment_name: MyApplication-Environment
  #         version_label: latest-${{github.SHA}}
  #         region: us-west-2
  #         deployment_package: app.jar


